cd wilds

echo "Run model_size=B_16 pretrained=False"
python run_expt.py -d fmow --model vit --algorithm ERM  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm groupDRO  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm deepCORAL  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm IRM  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm DANN  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm FixMatch  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm PseudoLabel  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm NoisyStudent  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1

echo "Run model_size=B_32 pretrained=False"
python run_expt.py -d fmow --model vit --algorithm ERM  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm groupDRO  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm deepCORAL  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm IRM  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm DANN  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm FixMatch  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm PseudoLabel  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm NoisyStudent  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=B_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1

echo "Run model_size=L_32 pretrained=False"
python run_expt.py -d fmow --model vit --algorithm ERM  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm groupDRO  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm deepCORAL  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm IRM  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm DANN  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm FixMatch  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm PseudoLabel  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm NoisyStudent  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_32 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1

# L_16 ViT is only available with pretrained=False
echo "Run model_size=L_16 pretrained=False"
python run_expt.py -d fmow --model vit --algorithm ERM  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm groupDRO  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm deepCORAL  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm IRM  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm DANN  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm FixMatch  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm PseudoLabel  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
python run_expt.py -d fmow --model vit --algorithm NoisyStudent  --root_dir ./data --loader_kwargs pin_memory=True --loader_kwargs "num_workers=26" --model_kwargs model_size=L_16 pretrained=False --use_wandb=True --wandb_kwargs project="wilds" entity="the-wild-guess" --device=1
